# Use zsh as default shell
set-option -g default-shell /usr/bin/zsh
set-option -g default-command /usr/bin/zsh

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind [ split-window -h
bind ] split-window -v 

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind p display-panes
bind o kill-pane


bind q new-window
bind e previous-window
bind r next-window
bind w kill-window

bind 1 choose-tree -Z
bind 2 new-session
bind 3 source-file ~/.tmux.conf \; display "Reloaded!!!"

##### ===== BELL / ACTIVITY =====
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

##### ===== CLOCK =====
setw -g clock-mode-colour red

##### ===== COPY MODE =====
setw -g mode-style ' bg=white fg=black '

##### ===== PANES =====
set -g pane-border-style 'fg=black'
set -g pane-active-border-style 'fg=black'

##### ===== STATUS BAR =====
set -g status on
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=white'

set -g status-left ''
set -g status-left-length 10

##### ===== WINDOW STATUS =====
setw -g window-status-style 'fg=white bg=black'
setw -g window-status-format ' #[bold]#I #[fg=white]#W - #[bold]#{pane_current_path} '
setw -g window-status-current-style 'fg=white bg=blue'
setw -g window-status-current-format ' #[fg=white]#I #[fg=white]#W - #[bold]#{pane_current_path} '

setw -g window-status-bell-style 'fg=black bg=green bold'

##### ===== MESSAGES =====
set -g message-style 'fg=black bg=green bold'

set -g status-left ' #[fg=white bold]#H '
set -g status-left-length 100

##### ===== STATUS RIGHT (CPU + RAM + TIME) =====
set -g status-right-style 'fg=white bg=blue bold'

set -g status-interval 1
set -g status-right ' CPU: #(top -bn1 | grep "Cpu(s)" | awk "{print 100-\$8}")% | RAM: #(free -m | awk "/Mem:/ {printf int(\$3/\$2*100)}")% | %d-%m-%Y %H:%M '
set -g status-right-length 100
